### ISSUE TITLE
Input Field Character Limit Restriction

### ISSUE THREAD

**Issue by alexmanner** [AdieLaine/multi-agent-reasoning#1]
**Issue Description:**

When using the app, the input field for prompts is capped at approximately 866 characters. This limitation occurs before pressing enter, meaning any text longer than 866 characters gets cut off. This hinders the ability to provide more extensive context for prompts.

**Steps to Reproduce:**

    Start the app.
    Attempt to input a prompt longer than 866 characters.
    Observe that the input is truncated after 866 characters.

**Expected Behavior:** The input field should allow for longer text, ideally without an arbitrary character limit, or be configured to handle multi-line inputs for longer prompts.

Environment:

    Python version: 3.11.10
    Operating system: MacOS
    Terminal/Console: MacOS Terminal

**Comment by AdieLaine** [comment]
Thank you for bringing this issue update.

**Issue Summary:**

- When using the app, the prompt input field is capped at approximately **866 characters**.
- This limitation occurs **before pressing enter**, meaning any text longer than 866 characters gets cut off.
- This hinders the ability to provide more extensive context for prompts.

**Cause Analysis:**

- The character limit you're experiencing is not imposed by the application code itself but is likely due to the way the app handles input in the terminal environment.
- The standard `input()` function in Python, which reads a line from input until a newline is encountered, can have limitations based on the terminal or command-line interface being used.
- Some terminals or consoles have a maximum line length, and inputting more than this limit can cause the input to be truncated.
